# Generated by Django 3.1 on 2021-08-05 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Цена')),
                ('discount', models.PositiveIntegerField(blank=True, default=0, verbose_name='Скидка, %')),
                ('year_of_issue', models.PositiveIntegerField()),
                ('mileage', models.PositiveIntegerField(default=0, verbose_name='Пробег, км')),
                ('engine', models.CharField(blank=True, choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('electro', 'Электро'), ('hybrid', 'Гибрид'), ('diesel gas', 'Дизель+газ'), ('petrol gas', 'Бензин+газ'), ('gas', 'Газ'), ('not specified', 'Не указано')], default='not specified', max_length=30, verbose_name='Двигатель')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('number_of_seats', models.PositiveIntegerField(verbose_name='Количство мест')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Объём двигателя, см3')),
                ('power', models.PositiveIntegerField(blank=True, verbose_name='Мощность, л. с.')),
                ('transmission', models.CharField(blank=True, choices=[('automatic', 'Автомат'), ('mechanical', 'Механическая'), ('pneumatic', 'Пневматическая'), ('robot', 'Робот'), ('variable', 'Вариатор'), ('not specified', 'Не указано')], default='not specified', max_length=20, verbose_name='Коробка')),
                ('steering_wheel', models.CharField(choices=[('right', 'Правый'), ('left', 'Левый')], default='left', max_length=20, verbose_name='Руль')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет')),
                ('created', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.product')),
            ],
        ),
    ]
