# Generated by Django 3.1 on 2021-08-07 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
