# Generated by Django 3.1 on 2021-08-08 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
